package io.github.drompincen.javaclawv1.runtime.agent.llm;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.drompincen.javaclawv1.persistence.document.TestPromptDocument;
import io.github.drompincen.javaclawv1.persistence.repository.TestPromptRepository;
import io.github.drompincen.javaclawv1.runtime.agent.graph.AgentState;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

@DataMongoTest
@ActiveProfiles("test")
@ContextConfiguration(classes = TestMongoConfiguration.class)
class TestModeLlmServiceTest {

    @Autowired
    private TestPromptRepository testPromptRepository;

    @Autowired
    private MongoTemplate mongoTemplate;

    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void clean() {
        for (String name : mongoTemplate.getCollectionNames()) {
            mongoTemplate.dropCollection(name);
        }
    }

    @Test
    void blockingResponse_writesPromptToMongo() {
        // Use a short timeout so the test doesn't wait 15s
        TestModeLlmService service = new TestModeLlmService(testPromptRepository, objectMapper, 2_000);

        AgentState state = new AgentState();
        state.setThreadId("session-1");
        state.setCurrentAgentId("controller");
        state.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "list files"))
        ));

        service.blockingResponse(state);

        List<TestPromptDocument> docs = testPromptRepository.findAll();
        assertThat(docs).hasSize(1);
        TestPromptDocument doc = docs.get(0);
        assertThat(doc.getAgentId()).isEqualTo("controller");
        assertThat(doc.getSessionId()).isEqualTo("session-1");
        assertThat(doc.getPrompt()).contains("list files");
        assertThat(doc.getUserQuery()).isEqualTo("list files");
    }

    @Test
    void blockingResponse_usesFallbackOnTimeout() {
        TestModeLlmService service = new TestModeLlmService(testPromptRepository, objectMapper, 2_000);

        AgentState state = new AgentState();
        state.setThreadId("session-2");
        state.setCurrentAgentId("coder");
        state.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "read pom.xml"))
        ));

        String response = service.blockingResponse(state);

        // Should return the fallback (generated by TestResponseGenerator for "coder" agent)
        assertThat(response).isNotBlank();
        assertThat(response).doesNotContain("[ERROR]");

        // Verify fallback was also saved to the document
        TestPromptDocument doc = testPromptRepository.findAll().get(0);
        assertThat(doc.getLlmResponse()).isEqualTo(response);
        assertThat(doc.getResponseFallback()).isEqualTo(response);
        assertThat(doc.getDuration()).isNotNull();
        assertThat(doc.getResponseTimestamp()).isNotNull();
    }

    @Test
    void blockingResponse_returnsResponseWhenConsumerFillsIt() throws Exception {
        TestModeLlmService service = new TestModeLlmService(testPromptRepository, objectMapper, 10_000);

        AgentState state = new AgentState();
        state.setThreadId("session-3");
        state.setCurrentAgentId("pm");
        state.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "show sprint status"))
        ));

        // Run blockingResponse in background
        CompletableFuture<String> future = CompletableFuture.supplyAsync(() ->
                service.blockingResponse(state));

        // Wait for the document to appear, then simulate the consumer filling the response
        Thread.sleep(800);
        List<TestPromptDocument> docs = testPromptRepository.findAll();
        assertThat(docs).hasSize(1);

        TestPromptDocument doc = docs.get(0);
        doc.setLlmResponse("Sprint 42 is on track with 8 out of 10 tickets completed.");
        doc.setDuration(150L);
        doc.setResponseTimestamp(Instant.now());
        testPromptRepository.save(doc);

        // The service should pick up the response
        String response = future.get(5, TimeUnit.SECONDS);
        assertThat(response).isEqualTo("Sprint 42 is on track with 8 out of 10 tickets completed.");
    }

    @Test
    void blockingResponse_responseFallbackIsPreComputed() {
        TestModeLlmService service = new TestModeLlmService(testPromptRepository, objectMapper, 2_000);

        AgentState state = new AgentState();
        state.setThreadId("session-4");
        state.setCurrentAgentId("controller");
        state.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "read the readme file"))
        ));

        service.blockingResponse(state);

        TestPromptDocument doc = testPromptRepository.findAll().get(0);
        // Controller should delegate to "coder" for file-related queries
        assertThat(doc.getResponseFallback()).contains("delegate");
        assertThat(doc.getResponseFallback()).contains("coder");
    }

    @Test
    void enforcePromptCap_deletesOldest() {
        TestModeLlmService service = new TestModeLlmService(testPromptRepository, objectMapper, 1_000);

        // Fill up to MAX_PROMPTS (20) + 1 to trigger cleanup
        for (int i = 0; i < 21; i++) {
            AgentState state = new AgentState();
            state.setThreadId("session-cap");
            state.setCurrentAgentId("controller");
            state.setMessages(List.of(
                    new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "msg " + i))
            ));
            service.blockingResponse(state);
        }

        // Should have at most MAX_PROMPTS (20) documents
        long count = testPromptRepository.count();
        assertThat(count).isLessThanOrEqualTo(20);
    }

    // --- Scenario-based response tests ---

    @Test
    void blockingResponse_usesScenarioResponseWhenMatch() {
        ScenarioService scenarioService = new ScenarioService(objectMapper);
        scenarioService.setConfig(new ScenarioConfig("Test Project", "test", List.of(
                new ScenarioConfig.ScenarioStep("what is the sprint status?", "pm query", List.of(
                        new ScenarioConfig.AgentResponse("controller",
                                "{\"delegate\": \"pm\", \"subTask\": \"sprint status\"}"),
                        new ScenarioConfig.AgentResponse("pm",
                                "Sprint 3 is on track with 8/10 tickets done.")
                ))
        )));

        TestModeLlmService service = new TestModeLlmService(
                testPromptRepository, objectMapper, 2_000, scenarioService);

        // Test controller gets scenario response
        AgentState controllerState = new AgentState();
        controllerState.setThreadId("scenario-session-1");
        controllerState.setCurrentAgentId("controller");
        controllerState.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "what is the sprint status?"))
        ));

        String controllerResponse = service.blockingResponse(controllerState);
        assertThat(controllerResponse).contains("\"delegate\": \"pm\"");

        // Test pm gets scenario response
        AgentState pmState = new AgentState();
        pmState.setThreadId("scenario-session-1");
        pmState.setCurrentAgentId("pm");
        pmState.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "what is the sprint status?"))
        ));

        String pmResponse = service.blockingResponse(pmState);
        assertThat(pmResponse).isEqualTo("Sprint 3 is on track with 8/10 tickets done.");

        // Verify both responses are written to testPrompts
        List<TestPromptDocument> docs = testPromptRepository.findAll();
        assertThat(docs).hasSize(2);
        assertThat(docs).allSatisfy(doc -> {
            assertThat(doc.getLlmResponse()).isNotNull();
            assertThat(doc.getDuration()).isEqualTo(0L);
        });
    }

    @Test
    void blockingResponse_fallsBackWhenNoScenarioMatch() {
        ScenarioService scenarioService = new ScenarioService(objectMapper);
        scenarioService.setConfig(new ScenarioConfig("Test Project", "test", List.of(
                new ScenarioConfig.ScenarioStep("specific query", "test", List.of(
                        new ScenarioConfig.AgentResponse("controller", "specific response")
                ))
        )));

        TestModeLlmService service = new TestModeLlmService(
                testPromptRepository, objectMapper, 2_000, scenarioService);

        // Use a query that does NOT match the scenario
        AgentState state = new AgentState();
        state.setThreadId("scenario-fallback");
        state.setCurrentAgentId("controller");
        state.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "unmatched query"))
        ));

        String response = service.blockingResponse(state);

        // Falls back to TestResponseGenerator — should get delegation JSON
        assertThat(response).contains("delegate");
    }

    @Test
    void blockingResponse_scenarioCaseInsensitiveMatch() {
        ScenarioService scenarioService = new ScenarioService(objectMapper);
        scenarioService.setConfig(new ScenarioConfig("Test Project", "test", List.of(
                new ScenarioConfig.ScenarioStep("Show Sprint Status", "test", List.of(
                        new ScenarioConfig.AgentResponse("controller",
                                "{\"delegate\": \"pm\"}")
                ))
        )));

        TestModeLlmService service = new TestModeLlmService(
                testPromptRepository, objectMapper, 2_000, scenarioService);

        AgentState state = new AgentState();
        state.setThreadId("scenario-case");
        state.setCurrentAgentId("controller");
        state.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "show sprint status"))
        ));

        String response = service.blockingResponse(state);
        assertThat(response).contains("\"delegate\": \"pm\"");
    }

    @Test
    void blockingResponse_noScenarioService_behavesAsOriginal() {
        // No scenario service — original behavior
        TestModeLlmService service = new TestModeLlmService(testPromptRepository, objectMapper, 2_000);

        AgentState state = new AgentState();
        state.setThreadId("no-scenario");
        state.setCurrentAgentId("controller");
        state.setMessages(List.of(
                new java.util.HashMap<>(java.util.Map.of("role", "user", "content", "hello"))
        ));

        String response = service.blockingResponse(state);

        // Falls back to TestResponseGenerator
        assertThat(response).contains("delegate");
        assertThat(response).contains("generalist");
    }
}
