package io.github.drompincen.javaclawv1.protocol.event;

public enum EventType {
    USER_MESSAGE_RECEIVED,
    AGENT_STEP_STARTED,
    MODEL_TOKEN_DELTA,
    TOOL_CALL_PROPOSED,
    TOOL_CALL_APPROVED,
    TOOL_CALL_DENIED,
    TOOL_CALL_STARTED,
    TOOL_STDOUT_DELTA,
    TOOL_STDERR_DELTA,
    TOOL_PROGRESS,
    TOOL_RESULT,
    AGENT_STEP_COMPLETED,
    CHECKPOINT_CREATED,
    SESSION_STATUS_CHANGED,
    ERROR,

    // Multi-agent events
    AGENT_DELEGATED,
    AGENT_RESPONSE,
    AGENT_CHECK_REQUESTED,
    AGENT_CHECK_PASSED,
    AGENT_CHECK_FAILED,
    AGENT_SWITCHED,

    // Memory events
    MEMORY_STORED,
    MEMORY_RECALLED,
    MEMORY_DISTILLED,

    // Human search events
    SEARCH_REQUESTED,
    SEARCH_RESPONSE_SUBMITTED,

    // Phase 2: project management events
    TICKET_CREATED,
    TICKET_UPDATED,
    IDEA_PROMOTED,
    REMINDER_TRIGGERED,
    APPROVAL_REQUESTED,
    APPROVAL_RESPONDED,
    RESOURCE_ASSIGNED,

    // Extraction events
    EXTRACTION_STARTED,
    EXTRACTION_COMPLETED,

    // Objective agent events
    OBJECTIVE_COVERAGE_COMPUTED,
    OBJECTIVE_UPDATED,
    OBJECTIVE_GAP_DETECTED,
    OBJECTIVE_TICKET_MAPPED,

    // Reconcile agent events
    RECONCILE_STARTED,
    RECONCILE_COMPLETED,
    RECONCILE_DELTA_FOUND,
    DELTA_PACK_CREATED,
    BLINDSPOT_CREATED,
    BLINDSPOT_ACKNOWLEDGED,
    BLINDSPOT_RESOLVED,

    // Plan agent events
    PHASE_CREATED,
    PHASE_UPDATED,
    PHASE_TRANSITION_RECOMMENDED,
    MILESTONE_CREATED,
    MILESTONE_UPDATED,
    MILESTONE_AT_RISK,
    MILESTONE_MISSED,
    PLAN_ARTIFACT_GENERATED,

    // Intake triage events
    INTAKE_RECEIVED,
    INTAKE_CLASSIFIED,
    INTAKE_DISPATCHED,

    // Checklist agent events
    CHECKLIST_CREATED,
    CHECKLIST_UPDATED,
    CHECKLIST_COMPLETED,
    CHECKLIST_TEMPLATE_CREATED,

    // Thread agent events
    THREAD_CREATED,
    THREAD_RENAMED,
    THREAD_MERGED,
    THREAD_EVIDENCE_ATTACHED,
    THREAD_IDEA_PROMOTED,

    // Resource agent events
    RESOURCE_UNASSIGNED,
    RESOURCE_OVERLOADED,
    RESOURCE_UNDERUTILIZED,
    CAPACITY_REPORT_GENERATED,
    ASSIGNMENT_SUGGESTED,
    RESOURCE_RISK_DETECTED,

    // Scheduler events
    EXEC_PLANNED,
    EXEC_CLAIMED,
    EXEC_STARTED,
    EXEC_FINISHED,
    EXEC_RETRYING,
    EXEC_CANCELLED,
    SCHEDULE_CREATED,
    SCHEDULE_UPDATED,
    SCHEDULE_DISABLED,
    MIDNIGHT_REBUILD
}
