package io.github.drompincen.javaclawv1.protocol.event;

public enum EventType {
    USER_MESSAGE_RECEIVED,
    AGENT_STEP_STARTED,
    MODEL_TOKEN_DELTA,
    TOOL_CALL_PROPOSED,
    TOOL_CALL_APPROVED,
    TOOL_CALL_DENIED,
    TOOL_CALL_STARTED,
    TOOL_STDOUT_DELTA,
    TOOL_STDERR_DELTA,
    TOOL_PROGRESS,
    TOOL_RESULT,
    AGENT_STEP_COMPLETED,
    CHECKPOINT_CREATED,
    SESSION_STATUS_CHANGED,
    ERROR,

    // Multi-agent events
    AGENT_DELEGATED,
    AGENT_RESPONSE,
    AGENT_CHECK_REQUESTED,
    AGENT_CHECK_PASSED,
    AGENT_CHECK_FAILED,
    AGENT_SWITCHED,

    // Memory events
    MEMORY_STORED,
    MEMORY_RECALLED,
    MEMORY_DISTILLED,

    // Human search events
    SEARCH_REQUESTED,
    SEARCH_RESPONSE_SUBMITTED,

    // Phase 2: project management events
    TICKET_CREATED,
    TICKET_UPDATED,
    IDEA_PROMOTED,
    REMINDER_TRIGGERED,
    APPROVAL_REQUESTED,
    APPROVAL_RESPONDED,
    RESOURCE_ASSIGNED
}
